name: Tests project
on: push
jobs:
  container-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Spago install
        run: npx spago install
      - name: Spago build
        run: npx spago build
      - name: Build test
        run: npm run build:performance
      - name: Bundle test
        run: npm run bundle:performance
      - name: Run test
        run: npm run test:performance
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            test-results